# permissions for end users to view appmeshconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appmeshconfig-viewer-role
rules:
- apiGroups:
  - mesh.symcn.com
  resources:
  - appmeshconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mesh.symcn.com
  resources:
  - appmeshconfigs/status
  verbs:
  - get
