# permissions for end users to edit configuredservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: configuredservice-editor-role
rules:
- apiGroups:
  - mesh.symcn.com
  resources:
  - configuredservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mesh.symcn.com
  resources:
  - configuredservices/status
  verbs:
  - get
