# permissions for end users to edit istioconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: istioconfig-editor-role
rules:
- apiGroups:
  - mesh.symcn.com
  resources:
  - istioconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mesh.symcn.com
  resources:
  - istioconfigs/status
  verbs:
  - get
