# permissions for end users to view istioconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: istioconfig-viewer-role
rules:
- apiGroups:
  - mesh.symcn.com
  resources:
  - istioconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mesh.symcn.com
  resources:
  - istioconfigs/status
  verbs:
  - get
