# permissions for end users to view meshconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: meshconfig-viewer-role
rules:
- apiGroups:
  - mesh.symcn.com
  resources:
  - meshconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mesh.symcn.com
  resources:
  - meshconfigs/status
  verbs:
  - get
