
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - mesh.symcn.com
  resources:
  - appmeshconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mesh.symcn.com
  resources:
  - appmeshconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mesh.symcn.com
  resources:
  - configuredservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mesh.symcn.com
  resources:
  - configuredservices/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mesh.symcn.com
  resources:
  - istioconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mesh.symcn.com
  resources:
  - istioconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mesh.symcn.com
  resources:
  - meshconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mesh.symcn.com
  resources:
  - meshconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mesh.symcn.com
  resources:
  - serviceaccessors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mesh.symcn.com
  resources:
  - serviceaccessors/status
  verbs:
  - get
  - patch
  - update
