# permissions for end users to view serviceaccessors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: serviceaccessor-viewer-role
rules:
- apiGroups:
  - mesh.symcn.com
  resources:
  - serviceaccessors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mesh.symcn.com
  resources:
  - serviceaccessors/status
  verbs:
  - get
