apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: appmeshconfigs.mesh.symcn.com
spec:
  group: mesh.symcn.com
  names:
    kind: AppMeshConfig
    listKind: AppMeshConfigList
    plural: appmeshconfigs
    singular: appmeshconfig
    shortNames:
      - amc
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
