apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: serviceaccessors.mesh.symcn.com
spec:
  group: mesh.symcn.com
  names:
    kind: ServiceAccessor
    listKind: ServiceAccessorList
    plural: serviceaccessors
    singular: serviceaccessor
    shortNames:
      - svca
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
