apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: istioconfigs.mesh.symcn.com
spec:
  group: mesh.symcn.com
  names:
    kind: IstioConfig
    listKind: IstioConfigList
    plural: istioconfigs
    singular: istioconfig
    shortNames:
      - isc
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
