apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: meshconfigs.mesh.symcn.com
spec:
  group: mesh.symcn.com
  names:
    kind: MeshConfig
    listKind: MeshConfigList
    plural: meshconfigs
    singular: meshconfig
    shortNames:
      - mc
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
