apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: configuredservices.mesh.symcn.com
spec:
  group: mesh.symcn.com
  names:
    kind: ConfiguredService
    listKind: ConfiguredServiceList
    plural: configuredservices
    singular: configuredservice
    shortNames:
      - cfgs
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
